# Generated by Django 5.0.7 on 2024-07-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
